Remove nodejs dependencies, add slightly better validation
WatchBeam/carina pull request #13
Opened 2017-02-09 15:24 UTC by SimonSchick

This is a byproduct of trying to fix AOT builds and might not be required anymore, don't want to drop dead this work tho.
- replacing the single querystring call with some basic forward validation
- replacing `events` with a barebone implementation

2017-02-11 23:19 UTC, SimonSchick commented
Ignore breaking build, carina tests are flaky...

2017-02-12 01:21 UTC, ProbablePrime commented
As talked about in slack not a fan of removing `events` here

2017-02-12 01:34 UTC, jamesbirtles requested changes

2017-02-12 01:34 UTC, UnwrittenFun commented on tsconfig.json
> +        "emitDecoratorMetadata": true,
Neither of these are needed

2017-02-12 01:34 UTC, UnwrittenFun commented on webpack.config.js
> +            { test: /\.json$/, loaders: ['json-loader'] },
you can actually just remove this line. webpack 2 deals with json by default

2017-02-12 01:34 UTC, UnwrittenFun commented on webpack.config.js
> +        extensions: ['.webpack.js', '.web.js', '.ts', '.js'],
might as well just make this `['.js', '.ts']`

2017-02-12 01:34 UTC, UnwrittenFun commented on src/events.ts
> +
👎 No need to write our own here

2017-02-12 01:51 UTC, SimonSchick commented on src/events.ts
> +
Can we avoid it being bundled like 10x in fe2 then?

2017-02-12 01:53 UTC, UnwrittenFun commented on src/events.ts
> +
Maybe? I don't know what the issue is, but doing this just means we can't ever optimise there

2017-02-12 02:27 UTC, jamesbirtles approved these changes

2017-02-13 17:30 UTC, connor4312 commented on package.json
> +    "cross-env": "^3.1.4",
Unused?

2017-02-13 17:32 UTC, SimonSchick commented on package.json
> +    "cross-env": "^3.1.4",
Good catch, I had to use it for a moment, but then removed it!

2017-02-13 17:33 UTC, connor4312 approved these changes
Approving pending dropping cross-env 😄

2017-02-23 12:44 UTC, SimonSchick commented
I never merged this >.>

2017-02-23 12:45 UTC, merged